
   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlapp-deployment
  labels:
    app: mlapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlapp
  template:
    metadata:
      labels:
        app: mlapp 
    spec:
      containers:
      - name: nodeserver
        image: diabetes-model:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: mlapp-service
spec:
  selector:
    app: mlapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110